import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useError } from "../context/ErrorContext";
import { useState } from "react";
import { useEffect } from "react";
import type { NFT as NFTType } from "../components/NFT/Display";
import NFTDisplay from "../components/NFT/Display";
import BuyModal from "../components/Buy/BuyModal";
import { useContracts } from "../context/ContractsContext";
import { useCartInfo } from "../context/CartInfoContext";
import NFTList from "../components/NFT/NFTList";
import { ChainId } from "../utils/constants";
import { BigNumber } from "ethers";

const Home: NextPage = () => {
  //@dev inherit NFT and extend interface for specific use cases if required
  // setting default nft selected for now
  const router = useRouter();
  const { chainId } = router.query;
  const { setContracts } = useContracts();
  const { cartInfo, setCartInfo } = useCartInfo();
  const setShowBuyModal = (showmodal: boolean) => {
    setCartInfo((prev: any) => ({
      ...prev,
      showModal: showmodal,
    }));
  };
  // @dev initialise contractsfor query om mian net change to
  // useEffect(()=>{
  //  (async()=> {
  //     if(Number(chainId) == 97){
  //       const queryContractsTest = await getQueryContacts(ChainId.BSC_TEST)
  //       setContracts(queryContractsTest)
  //       console.log("yoo")
  //     }
  //     else{
  //       const queryContractsMain = await getQueryContacts(ChainId.BSC_MAIN)
  //       setContracts(queryContractsMain)
  //     }
  //   })()
  // },[])

  return (
    <div className={styles.container}>
      {/* add proect header values */}
      <Head>
        <title>MintEngine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className="area">
          <ul className="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
        </div> */}
        <NFTDisplay></NFTDisplay>
        {/* *buy button opens modal wher we select amount and currency to pay with */}
        <div>
          <button
            className="checkOut"
            disabled={cartInfo.totalPrice.eq(BigNumber.from(0))}
            onClick={() => setShowBuyModal(true)}
          >
            CheckOut
          </button>
        </div>
      </main>
      {cartInfo?.showModal && <BuyModal></BuyModal>}
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
